[package]
name = "understood"
version = "0.2.2"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
image = "0.24.0"
similars_lib = { git = "https://github.com/jerryshell/similars" }
rand = "0.8.4"

[profile.release]
lto = true
