[package]
name = "understood"
version = "0.3.5"
edition = "2021"
authors = ["github.com/jerryshell"]

[dependencies]
image = "0.24.0"
similars_lib = { git = "https://github.com/jerryshell/similars" }
rand = "0.8.4"
threadpool = "1.8.1"
num_cpus = "1.13.1"
clap = { version = "3.0.14", features = ["derive"] }

[profile.release]
lto = true
