on: [push]

name: ci-amd64-linux

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: understood-amd64-linux
          path: target/x86_64-unknown-linux-gnu/release/understood
