on: [push]

name: ci-armv7hf-linux

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: understood-armv7hf-linux
          path: target/armv7-unknown-linux-gnueabihf/release/understood
